# Generated by Django 5.2.4 on 2025-07-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uats', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
